server:
  port: 8004

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false # 是否拉取服务列表，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8003/eureka
  instance:
    #服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 90
    #服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
