
server:
  port: 8102

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/sc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: p
      filters: stat
      max-active: 100
      initial-size: 5
      max-wait: 60000
      min-idle: 2
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  application:
    name: user-service

eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8003/eureka,http://127.0.0.1:8004/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
  server:
    enable-self-preservation: false # 关闭自我保护模式（默认为打开）
    eviction-interval-timer-in-ms: 1000 #   扫描失效服务的间隔时间为1s（默认为60s）
