spring:
  flyway:
    baseline-on-migrate: true
    clean-on-validation-error: true
    locations: classpath:/db/migration
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:mybatis-config.xml
